import type { SignData } from '../../types'

/**
 * MUTCD 2009 Table 2E-1 (and 2D guide) sign designations for Chapter 6H Typical Applications
 * that are not in Table 6F-1. Entries already in {@link tcpCatalog} (E5-1, M1-1, M4-6, D1-2) are omitted.
 * Green guide styling until SHS artwork is linked.
 */
export const MUTCD_6H_SUPPLEMENT: SignData[] = [
  { id: 'ta6hE1_5P', label: 'EXIT # (P)', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E1-5P' },
  { id: 'ta6hE1_5aP', label: 'LEFT (P)', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E1-5aP' },
  { id: 'ta6hE1_5bP', label: 'L EXIT# (P)', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E1-5bP' },
  { id: 'ta6hE5_1a', label: 'GORE + #', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E5-1a' },
  { id: 'ta6hE5_1bP', label: 'EXIT# (P)', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E5-1bP' },
  { id: 'ta6hE5_1c', label: 'NARROW GORE', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E5-1c' },
  { id: 'ta6hE6_2', label: 'PULL-THRU', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E6-2' },
  { id: 'ta6hE6_2a', label: 'PULL-THR 2', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E6-2a' },
  { id: 'ta6hE11_1', label: 'EXIT ONLY', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E11-1' },
  { id: 'ta6hE11_1a', label: 'EXIT', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E11-1a' },
  { id: 'ta6hE11_1b', label: 'ONLY', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E11-1b' },
  { id: 'ta6hE11_1c', label: 'EXIT ONLY+', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E11-1c' },
  { id: 'ta6hE11_1d', label: 'EXIT ONL 1D', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E11-1d' },
  { id: 'ta6hE11_1e', label: 'EXIT ONL 2A', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E11-1e' },
  { id: 'ta6hE11_1f', label: 'EXIT ONL 2B', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E11-1f' },
  { id: 'ta6hE11_2', label: 'LEFT', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E11-2' },
  { id: 'ta6hE13_1P', label: 'GORE SPD (P)', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E13-1P' },
  { id: 'ta6hE13_2', label: 'EXIT DIR SPD', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E13-2' },
  { id: 'ta6hM1_2', label: 'BUS LOOP', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M1-2' },
  { id: 'ta6hM1_3', label: 'BUS SPUR', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M1-3' },
  { id: 'ta6hM1_4', label: 'US SHIELD', shape: 'shield', color: '#fff', textColor: '#111', border: '#111', mutcd: 'M1-4' },
  { id: 'ta6hM1_5', label: 'STATE SHLD', shape: 'shield', color: '#fff', textColor: '#111', border: '#111', mutcd: 'M1-5' },
  { id: 'ta6hM1_6', label: 'COUNTY RT', shape: 'shield', color: '#3b82f6', textColor: '#fbbf24', border: '#111', mutcd: 'M1-6' },
  { id: 'ta6hM1_7', label: 'FOREST RT', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M1-7' },
  { id: 'ta6hM1_10', label: 'I-SYS', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M1-10' },
  { id: 'ta6hM1_10a', label: 'I-SYS A', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M1-10a' },
  { id: 'ta6hM2_1', label: 'JCT', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M2-1' },
  { id: 'ta6hM2_2', label: 'JCT COMBO', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M2-2' },
  { id: 'ta6hM3_1', label: 'NORTH', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M3-1' },
  { id: 'ta6hM3_2', label: 'SOUTH', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M3-2' },
  { id: 'ta6hM3_3', label: 'EAST', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M3-3' },
  { id: 'ta6hM3_4', label: 'WEST', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M3-4' },
  { id: 'ta6hM4_1', label: 'ALT', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M4-1' },
  { id: 'ta6hM4_1a', label: 'ALT A', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M4-1a' },
  { id: 'ta6hM4_2', label: 'BYPASS', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M4-2' },
  { id: 'ta6hM4_3', label: 'BUSINESS', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M4-3' },
  { id: 'ta6hM4_4', label: 'TRUCK (AUX)', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M4-4' },
  { id: 'ta6hM4_5', label: 'TO (AUX)', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M4-5' },
  { id: 'ta6hM4_7', label: 'TEMP', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M4-7' },
  { id: 'ta6hM4_7a', label: 'TEMP A', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M4-7a' },
  { id: 'ta6hM4_14', label: 'BEGIN (AUX)', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M4-14' },
  { id: 'ta6hM5_1', label: 'ADV TURN 1', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M5-1' },
  { id: 'ta6hM5_2', label: 'ADV TURN 2', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M5-2' },
  { id: 'ta6hM5_3', label: 'ADV TURN 3', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M5-3' },
  { id: 'ta6hM5_4', label: 'LANE 4', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M5-4' },
  { id: 'ta6hM5_5', label: 'LANE 5', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M5-5' },
  { id: 'ta6hM5_6', label: 'LANE 6', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M5-6' },
  { id: 'ta6hM6_1', label: 'DIR A', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M6-1' },
  { id: 'ta6hM6_2', label: 'DIR B', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M6-2' },
  { id: 'ta6hM6_2a', label: 'DIR B2', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M6-2a' },
  { id: 'ta6hM6_3', label: 'DIR C', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M6-3' },
  { id: 'ta6hM6_4', label: 'DIR D', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M6-4' },
  { id: 'ta6hM6_5', label: 'DIR E', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M6-5' },
  { id: 'ta6hM6_6', label: 'DIR F', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M6-6' },
  { id: 'ta6hM6_7', label: 'DIR G', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'M6-7' },
  { id: 'ta6hD1_1', label: 'DEST 1LN', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D1-1' },
  { id: 'ta6hD1_1a', label: 'DEST1+DIST', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D1-1a' },
  { id: 'ta6hD1_2a', label: 'DEST2+DIST', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D1-2a' },
  { id: 'ta6hD1_3', label: 'DEST 3LN', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D1-3' },
  { id: 'ta6hD1_3a', label: 'DEST3+DIST', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D1-3a' },
  { id: 'ta6hD2_1', label: 'DIST 1LN', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D2-1' },
  { id: 'ta6hD2_2', label: 'DIST 2LN', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D2-2' },
  { id: 'ta6hD2_3', label: 'DIST 3LN', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D2-3' },
  { id: 'ta6hD3_1', label: 'STREET 1L', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D3-1' },
  { id: 'ta6hD3_1a', label: 'STREET1A', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D3-1a' },
  { id: 'ta6hD3_2', label: 'ADV ST NAME', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D3-2' },
  { id: 'ta6hD4_2', label: 'PARK-RIDE', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D4-2' },
  { id: 'ta6hD6_4', label: 'NS BYWAY', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D6-4' },
  { id: 'ta6hD6_4a', label: 'NSB SM', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D6-4a' },
  { id: 'ta6hD8_1', label: 'WGH STN MI', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D8-1' },
  { id: 'ta6hD8_2', label: 'WGH NXT R', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D8-2' },
  { id: 'ta6hD8_3', label: 'WGH ARW', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D8-3' },
  { id: 'ta6hD13_1', label: 'CROSSOVER1', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D13-1' },
  { id: 'ta6hD13_2', label: 'CROSSOVER2', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D13-2' },
  { id: 'ta6hD13_3', label: 'FWY ENTER', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D13-3' },
  { id: 'ta6hD13_3a', label: 'FWY ENT+ARW', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D13-3a' },
  { id: 'ta6hD15_1', label: 'LN+DEST OVH', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D15-1' },
  { id: 'ta6hD17_1', label: 'TRK LN MI', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D17-1' },
  { id: 'ta6hD17_2', label: 'TRK LN AHD', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D17-2' },
  { id: 'ta6hD17_7', label: 'SLOW TURN MI', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'D17-7' },
]
