import type { SignData } from '../../types'

/**
 * Signs required to cover every atomic MUTCD designation in Table 6F-1 (2009)
 * that was not already present in {@link tcpCatalog}. Labels are abbreviated
 * for the canvas; graphics use generic TTC styling until SHS artwork is linked.
 */
export const MUTCD_6F1_SUPPLEMENT: SignData[] = [
  { id: 'ttcE5_2', label: 'EXIT OPEN AHEAD', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E5-2' },
  { id: 'ttcE5_2a', label: 'EXIT CLOSED AHEAD', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E5-2a' },
  { id: 'ttcE5_3', label: 'EXIT ONLY AHEAD', shape: 'rect', color: '#22c55e', textColor: '#fff', mutcd: 'E5-3' },
  { id: 'ttcG20_4', label: 'PILOT CAR FOLLOW', shape: 'rect', color: '#f97316', textColor: '#111', mutcd: 'G20-4' },
  { id: 'ttcG20_5aP', label: 'WORK ZONE (PLAQUE)', shape: 'rect', color: '#f97316', textColor: '#111', mutcd: 'G20-5aP' },
  { id: 'ttcM4_9a', label: 'BIKE / PED DETOUR', shape: 'rect', color: '#f97316', textColor: '#111', mutcd: 'M4-9a' },
  { id: 'ttcM4_9b', label: 'PEDESTRIAN DETOUR', shape: 'rect', color: '#f97316', textColor: '#111', mutcd: 'M4-9b' },
  { id: 'ttcM4_9c', label: 'BICYCLE DETOUR', shape: 'rect', color: '#f97316', textColor: '#111', mutcd: 'M4-9c' },
  { id: 'ttcR1_2aP', label: 'TO ONCOMING TRF', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R1-2aP' },
  { id: 'ttcR1_7', label: 'WAIT ON STOP', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R1-7' },
  { id: 'ttcR1_8', label: 'GO ON SLOW', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R1-8' },
  { id: 'ttcR11_3a', label: 'ROAD CLSD, LOCAL', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R11-3a' },
  { id: 'ttcR11_3b', label: 'LOCAL TRF (R11-3B)', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R11-3b' },
  { id: 'ttcR12_2', label: 'WEIGHT TONS (R12-2)', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R12-2' },
  { id: 'ttcR12_5', label: 'WEIGHT (SYM)', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R12-5' },
  { id: 'ttcR2_10', label: 'BEGIN HIGHER FINES', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R2-10' },
  { id: 'ttcR2_11', label: 'END HIGHER FINES', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R2-11' },
  { id: 'ttcR2_12', label: 'END WZ SPEED', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R2-12' },
  { id: 'ttcR2_6P', label: 'FINES HIGHER', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R2-6P' },
  { id: 'ttcR2_6aP', label: 'FINES DOUBLE', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R2-6aP' },
  { id: 'ttcR2_6bP', label: 'XX DOLLAR FINE', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R2-6bP' },
  { id: 'ttcR3_18', label: 'NO TURN ON RED (R3-18)', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R3-18' },
  { id: 'ttcR3_27', label: 'MOVEMENT (R3-27)', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R3-27' },
  { id: 'ttcR3_3', label: 'NO TURNS (R3-3)', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R3-3' },
  { id: 'ttcR3_5', label: 'MAND. MOV. 1 LN', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R3-5' },
  { id: 'ttcR3_6', label: 'OPT. MOV. 1 LN', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R3-6' },
  { id: 'ttcR3_7', label: 'MAND. PLAQUE (TXT)', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R3-7' },
  { id: 'ttcR3_8', label: 'ADV. INT. LN. CTL', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R3-8' },
  { id: 'ttcR4_2', label: 'PASS WITH CARE', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R4-2' },
  { id: 'ttcR4_7c', label: 'NARROW, KEEP RGT', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R4-7c' },
  { id: 'ttcR4_9', label: 'STAY IN LANE', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R4-9' },
  { id: 'ttcR6_2', label: 'ONE-WAY (VERT)', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R6-2' },
  { id: 'ttcR8_3', label: 'NO PARK (SYM)', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R8-3' },
  { id: 'ttcR9_11', label: 'SDWK CLSD, X HERE', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R9-11' },
  { id: 'ttcR9_11a', label: 'SDWK CLSD, X AHD', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R9-11a' },
  { id: 'ttcR9_9', label: 'SIDEWALK CLOSED (R9-9)', shape: 'rect', color: '#fff', textColor: '#111', border: '#111', mutcd: 'R9-9' },
  { id: 'ttcW1_1', label: 'TURN / CURVE (ARR)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W1-1' },
  { id: 'ttcW1_3', label: 'TURN / WND (R)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W1-3' },
  { id: 'ttcW1_4b', label: 'REV. CURV (2LN)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W1-4b' },
  { id: 'ttcW1_4c', label: 'REV. CURV (3+LN)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W1-4c' },
  { id: 'ttcW1_8', label: 'CHEVRON AHEAD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W1-8' },
  { id: 'ttcW11_10', label: 'TRUCK CROSS AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W11-10' },
  { id: 'ttcW12_1', label: 'DOUBLE ARROW AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W12-1' },
  { id: 'ttcW13_1P', label: 'ADV. SPEED (P)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W13-1P' },
  { id: 'ttcW13_4P', label: 'ON RAMP (P)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W13-4P' },
  { id: 'ttcW14_3', label: 'NO PASS ZONE', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W14-3' },
  { id: 'ttcW16_2P', label: 'XX FEET (P)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W16-2P' },
  { id: 'ttcW20_3', label: 'ROAD (ST) CLOSED AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W20-3' },
  { id: 'ttcW20_5a', label: 'TWO LANES CLSD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W20-5a' },
  { id: 'ttcW21_1', label: 'WORKERS (SYM)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W21-1' },
  { id: 'ttcW21_3', label: 'MACHINERY AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W21-3' },
  { id: 'ttcW21_4', label: 'SLOW VEH. AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W21-4' },
  { id: 'ttcW21_5b', label: 'SH. CLSD (DIST.)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W21-5b' },
  { id: 'ttcW23_1', label: 'SLOW TRAF. AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W23-1' },
  { id: 'ttcW23_2', label: 'NEW PATTERN AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W23-2' },
  { id: 'ttcW24_1', label: 'DBL. REV. CURV (1)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W24-1' },
  { id: 'ttcW24_1a', label: 'DBL. REV. CURV (2)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W24-1a' },
  { id: 'ttcW24_1b', label: 'DBL. REV. CURV (3)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W24-1b' },
  { id: 'ttcW24_1cP', label: 'ALL LANES (P)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W24-1cP' },
  { id: 'ttcW3_5a', label: 'XX MPH AHD (WZ)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W3-5a' },
  { id: 'ttcW4_5', label: 'MERGE (ALT)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W4-5' },
  { id: 'ttcW4_5P', label: 'NO MERGE (P)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W4-5P' },
  { id: 'ttcW4_6', label: 'ADDED (ALT)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W4-6' },
  { id: 'ttcW5_4', label: 'RAMP NARROWS', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W5-4' },
  { id: 'ttcW6_4', label: 'TWO-WAY (SML)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W6-4' },
  { id: 'ttcW7_3aP', label: 'NEXT XX MI (P)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W7-3aP' },
  { id: 'ttcW8_11', label: 'UNEVEN LANES', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W8-11' },
  { id: 'ttcW8_12', label: 'NO CENTER LINE', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W8-12' },
  { id: 'ttcW8_15', label: 'GROOVED PAVT.', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W8-15' },
  { id: 'ttcW8_15P', label: 'M/C (P)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W8-15P' },
  { id: 'ttcW8_17P', label: 'SH. DROP (P)', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W8-17P' },
  { id: 'ttcW8_18', label: 'FLOOD RISK AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W8-18' },
  { id: 'ttcW8_2', label: 'DIP AHEAD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W8-2' },
  { id: 'ttcW8_23', label: 'NO SHOULDER AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W8-23' },
  { id: 'ttcW8_24', label: 'STEEL PLATE AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W8-24' },
  { id: 'ttcW8_25', label: 'SHOULDER ENDS AHD', shape: 'diamond', color: '#f97316', textColor: '#111', mutcd: 'W8-25' },
]
